# This configuration is here to avoid Reek reporting smells in RubyCritic which are best practices for a Rails project
# See https://github.com/troessner/reek#working-with-rails for details
directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/jobs":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/channels":
    IrresponsibleModule:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
