development:
  adapter: async

test:
  adapter: async

staging:
  adapter: async

production:
  adapter: async
# Todo: Update traefik edge router to v2 to support tcp routing and try enabling this again
#  adapter: redis
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: workos_production
